// const DUMMY_COURSES = [
//     {
//         "id": "1",
//         "title": "Full Stack Web Development Bootcamp",
//         "instructor": "Lidetu Tadesse",
//         "level": "Intermediate",
//         "duration": "12 weeks",
//         "thumbnail": "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&q=80",
//         "rating": 4.9,
//         "enrolled": 3124,
//         "category": "Web Development",
//         "description": "Master both frontend and backend technologies. Learn HTML, CSS, JavaScript, React, Node.js, and more in this comprehensive bootcamp designed to take you from beginner to professional.",
//         "skills": ["HTML5 & CSS3", "Modern JavaScript", "React Framework", "Node.js & Express", "MongoDB Database", "RESTful APIs"]
//     },
//     {
//         "id": "2",
//         "title": "Practical Machine Learning",
//         "instructor": "Bereket Tesfaye Kebede",
//         "level": "Advanced",
//         "duration": "10 weeks",
//         "thumbnail": "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800&q=80",
//         "rating": 4.8,
//         "enrolled": 1742,
//         "category": "Data Science",
//         "description": "Learn how to design intelligent systems using real datasets. This course focuses on practical machine learning applications such as fraud detection, recommendation systems, and predictive analytics.",
//         "skills": ["Python for Data Science", "TensorFlow & Keras", "Scikit-Learn", "Data Preprocessing", "Neural Networks", "Deep Learning Models"]
//     },
//     {
//         "id": "3",
//         "title": "UI/UX Design for Modern Products",
//         "instructor": "Hana Alemayehu",
//         "level": "Beginner",
//         "duration": "8 weeks",
//         "thumbnail": "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80",
//         "rating": 4.7,
//         "enrolled": 2891,
//         "category": "Design",
//         "description": "Unlock your creative potential and learn the art of creating intuitive and visually stunning user interfaces. This course covers the entire design process from user research to high-fidelity prototyping.",
//         "skills": ["User Research", "Wireframing", "Figma", "Visual Hierarchy", "Prototyping", "Design Systems"]
//     },
//     {
//         "id": "4",
//         "title": "Cloud Engineering with AWS",
//         "instructor": "Samuel Getachew",
//         "level": "Intermediate",
//         "duration": "9 weeks",
//         "thumbnail": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80",
//         "rating": 4.6,
//         "enrolled": 2015,
//         "category": "Cloud Computing",
//         "description": "Gain hands-on experience with Amazon Web Services. Learn how to architect, deploy, and manage scalable and secure cloud infrastructure using industry-standard tools and practices.",
//         "skills": ["EC2 & S3", "AWS Lambda", "CloudFormation", "IAM Security", "VPC Networking", "Serverless Architecture"]
//     },
//     {
//         "id": "5",
//         "title": "Mobile App Development with Flutter",
//         "instructor": "Natnael Desta",
//         "level": "Intermediate",
//         "duration": "10 weeks",
//         "thumbnail": "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&q=80",
//         "rating": 4.8,
//         "enrolled": 2563,
//         "category": "Mobile Development",
//         "description": "Build high-performance, cross-platform mobile applications for iOS and Android from a single codebase. Learn Dart programming and the Flutter framework through hands-on projects.",
//         "skills": ["Dart Programming", "Flutter SDK", "State Management", "UI Layouts", "API Integration", "Firebase Backend"]
//     },
//     {
//         "id": "6",
//         "title": "Cybersecurity Foundations",
//         "instructor": "Meklit Girma",
//         "level": "Beginner",
//         "duration": "6 weeks",
//         "thumbnail": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80",
//         "rating": 4.7,
//         "enrolled": 1489,
//         "category": "Security",
//         "description": "Protect digital assets and learn the fundamentals of network security. This course introduces you to the concepts, tools, and techniques needed to defend against cyber threats.",
//         "skills": ["Network Security", "Threat Intelligence", "Cryptography", "Ethical Hacking", "Incident Response", "Identity Management"]
//     },
//     {
//         "id": "7",
//         "title": "Data Analytics with Python",
//         "instructor": "Abel Hailu",
//         "level": "Beginner",
//         "duration": "7 weeks",
//         "thumbnail": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
//         "rating": 4.8,
//         "enrolled": 2674,
//         "category": "Data Science",
//         "description": "Transform data into actionable insights using Python. Learn to manipulate, analyze, and visualize data using powerful libraries like Pandas, NumPy, and Matplotlib.",
//         "skills": ["Python Scripting", "Data Wrangling", "Statistical Analysis", "Data Visualization", "Pandas & NumPy", "SQL Integration"]
//     },
//     {
//         "id": "8",
//         "title": "Blockchain & Fintech Systems",
//         "instructor": "Yonas Bekele",
//         "level": "Advanced",
//         "duration": "11 weeks",
//         "thumbnail": "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&q=80",
//         "rating": 4.5,
//         "enrolled": 1321,
//         "category": "Blockchain",
//         "description": "Explore the future of finance and distributed ledger technology. Learn how blockchain works and how it is revolutionizing the fintech industry through smart contracts and decentralized applications.",
//         "skills": ["Blockchain Fundamentals", "Smart Contracts", "Solidity", "Crypto Economics", "Ethereum Network", "DEFI Applications"]
//     }
// ];